### ISSUE TITLE
Unity Editor crashes on startup: caused by ResonanceAudio:SetListenerGain

### ISSUE THREAD

**Issue by matthiaswitt** [resonance-audio/resonance-audio-unity-sdk#8] opened 2017-11-28 09:44 UTC
Editor.log:
```
[...]
Obtained 32 stack frames.
#0  0x00000125280a61 in SetListenerGain
#1  0x0000011e02491e in  (wrapper managed-to-native) ResonanceAudio:SetListenerGain (single) + 0xce (0x11e024850 0x11e02494d) [0x138493330 - Unity Child Domain]
#2  0x0000011e024705 in  ResonanceAudio:UpdateAudioListener (ResonanceAudioListener) + 0x105 (0x11e024600 0x11e02477f) [0x138493330 - Unity Child Domain]
#3  0x0000011e0244a7 in  ResonanceAudioListener:Update () + 0x77 (0x11e024430 0x11e0245c7) [0x138493330 - Unity Child Domain]
#4  0x0000011a73221a in  (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr) + 0xfa (0x11a732120 0x11a73234d) [0x138493330 - Unity Child Domain]
#5  0x00000137cda12e in mono_get_runtime_build_info
#6  0x00000137e05d56 in mono_runtime_invoke
#7  0x00000100ec1e0a in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
[...]
```

**Comment by anokta** [comment] 2017-11-28 19:33
Thanks for reporting! I believe this is caused by the same issue #7 reported by @Jmcm16.

We're looking at it to find out the root cause.

**Comment by anokta** [comment] 2017-11-28 19:35
Duplicate of #7

**Comment by anokta** [comment] 2017-11-28 19:41
Hi,

Just to verify, is this issue target platform/Unity version specific (i.e., indifferent from which platform you set in Build Settings)?

**Comment by ilmarioranen** [comment] 2017-11-29 15:27
Same issue for me (as commented in https://github.com/resonance-audio/resonance-audio-unity-sdk/issues/7 ).

Editor OS: Mac OS 10.12.6
Build platform: iOS
Unity version: Unity 2017 2.0p3 (patch release from just a few days ago, previous patch release seemed to have same problem).
I have the latest GVR SDK for Unity v1.110.0 and the latest (only) Resonance audio Unity SDK (1.0.0).

**Closed** 2017-11-29 19:03 UTC
Labels: bug
