### ISSUE TITLE
Unity 2017.3.1f1 + GearVR on Samsung Galaxy 8

### ISSUE THREAD

**Issue by AstralStew** [resonance-audio/resonance-audio-unity-sdk#22] opened 2018-02-28 11:08 UTC
We're having an issue getting the spatialiser working in Unity 2017.3.1f1 on the GearVR (Samsung Galaxy 8). We've set up Resonance Audio as both the Spatialiser Plugin and Ambisonic Decoder Plugin, and added a few audio sources around the level (some ambisonic and some standard), with attached/configured Resonance Audio Source components. The camera also has a Resonance Audio Listener attached (though I don't think we even need it, as we aren't using any advanced features like Reverb Zones or Occlusion). All of this works exactly as expected when playing the game in the Editor, no problems. 

However, once we build out onto the Galaxy 8, the audio sources still play but only as standard Unity Audio Sources - the ambisonics sound as though they coming from a single source point, and any settings we set in the Resonance Audio Source components have no effect on any of the other sounds. I've pored over the Getting Started and Developer Guides on the website and can't find anything we've missed for building to Android. I did find the following on the "VR Audio Spatializers" page in the Unity Manual:

"The spatializer plugins only work on the platforms that a VR device is supported on. If a device is not supported for a build target, Unity displays a warning that the plugin will not be included in the built application." 

... but there is no such warning (and in any case we are successfully building out onto a GearVR headset). I've wracked my brain for the last few days and can't figure it out! T_T 

Any idea what we're doing wrong? Any help at all would be appreciated!

EDIT: Not sure if this is the right place for this, so I'm copying it to StackOverflow. If so, feel free to delete.

**Comment by anokta** [comment] 2018-02-28 19:42
Hi,

This is caused by the Unity bug reported in issue #14. It should be fixed now with the latest patch releases 2017.3.1p1 and onwards ([https://unity3d.com/unity/qa/patch-releases](https://unity3d.com/unity/qa/patch-releases)). Please see issue #14 for further details.

duplicate of #14

**Comment by anokta** [comment] 2018-02-28 19:42
duplicate of #14

**Comment by anokta** [comment] 2018-02-28 19:43
Hi,

This is caused by the Unity bug reported in issue #14. It should be fixed now with the latest patch releases 2017.3.1p1 and onwards (https://unity3d.com/unity/qa/patch-releases). Please see issue #14 for further details.

Duplicate of #14

**Comment by anokta** [comment] 2018-02-28 19:44
Duplicate of #14

**Closed by anokta** 2018-02-28 19:44 UTC
